// <auto-generated />
import { NantoClient } from "@nanto/core";

export const manifest = "1e1306342fd5b6a5f1b1439ddf72269e6af8a2ff6b70e475084b5b7faf1ec44a" as const;
export type NantoResult<T, TError> = { ok: true; value: T } | { ok: false; error: TError };
export interface BuildProgress {
  percent: number;
  projectId: number;
}

export const BuildError = {
  Failed: "Failed",
} as const;
export type BuildError = typeof BuildError[keyof typeof BuildError];

export interface ProjectChange {
  kind: string;
  projectId: number;
}

export interface ProjectDetails {
  id: number;
  window: string;
}

export const OpenProjectError = {
  NotFound: "NotFound",
} as const;
export type OpenProjectError = typeof OpenProjectError[keyof typeof OpenProjectError];

export function createApp(client: NantoClient) {
  return {
    projects: {
      build: (projectId: number, $options?: { signal?: AbortSignal }) => client.stream<NantoResult<BuildProgress, BuildError>>(1725757109, { projectId }, $options?.signal),
      changed: {
        subscribe: (options?: { signal?: AbortSignal }) => client.subscribe<ProjectChange>(2877507624, options?.signal),
      },
      open: (projectId: number, $options?: { signal?: AbortSignal }) => client.invoke<NantoResult<ProjectDetails, OpenProjectError>>(1407742092, { projectId }, $options?.signal),
    },
  } as const;
}
