// <auto-generated />
import { NantoClient } from "@nanto/core";

export const manifest = "b927e80e466c42381abaebd28f16a94fefab8a294974f95e5aa3c91916609fa7" as const;
export type NantoResult<T, TError> = { ok: true; value: T } | { ok: false; error: TError };
/**
 * @source Phase2TestApi.cs:80
 */
export interface BuildProgress {
  /**
   * @source Phase2TestApi.cs:80
   */
  percent: number;
  /**
   * @source Phase2TestApi.cs:80
   */
  projectId: number;
}

/**
 * @source Phase2TestApi.cs:87
 */
export const BuildError = {
  /**
   * @source Phase2TestApi.cs:89
   */
  Failed: "Failed",
} as const;
export type BuildError = typeof BuildError[keyof typeof BuildError];

/**
 * @source Phase2TestApi.cs:78
 */
export interface ProjectChange {
  /**
   * @source Phase2TestApi.cs:78
   */
  kind: string;
  /**
   * @source Phase2TestApi.cs:78
   */
  projectId: number;
}

/**
 * @source Phase2TestApi.cs:76
 */
export interface ProjectDetails {
  /**
   * @source Phase2TestApi.cs:76
   */
  id: number;
  /**
   * @source Phase2TestApi.cs:76
   */
  window: string;
}

/**
 * @source Phase2TestApi.cs:82
 */
export const OpenProjectError = {
  /**
   * @source Phase2TestApi.cs:84
   */
  NotFound: "NotFound",
} as const;
export type OpenProjectError = typeof OpenProjectError[keyof typeof OpenProjectError];

export function createApp(client: NantoClient) {
  return {
    /**
     * @source Phase2TestApi.cs:6
     */
    projects: {
      /**
       * @source Phase2TestApi.cs:66
       */
      build: (projectId: number, $options?: { signal?: AbortSignal }) => client.stream<NantoResult<BuildProgress, BuildError>>(238439517, { projectId }, $options?.signal),
      /**
       * @source Phase2TestApi.cs:31
       */
      change: (projectId: number, $options?: { signal?: AbortSignal }) => client.invoke<void>(3694782280, { projectId }, $options?.signal),
      /**
       * @source Phase2TestApi.cs:13
       */
      changed: {
        subscribe: (options?: { signal?: AbortSignal }) => client.subscribe<ProjectChange>(2877507624, options?.signal),
      },
      /**
       * @source Phase2TestApi.cs:38
       */
      getActiveWaitCount: ($options?: { signal?: AbortSignal }) => client.invoke<number>(89415758, {  }, $options?.signal),
      /**
       * @source Phase2TestApi.cs:35
       */
      getCancellationCount: ($options?: { signal?: AbortSignal }) => client.invoke<number>(4212565545, {  }, $options?.signal),
      /**
       * @source Phase2TestApi.cs:20
       */
      open: (projectId: number, $options?: { signal?: AbortSignal }) => client.invoke<NantoResult<ProjectDetails, OpenProjectError>>(3836943207, { projectId }, $options?.signal),
      /**
       * @source Phase2TestApi.cs:41
       */
      wait: ($options?: { signal?: AbortSignal }) => client.invoke<void>(3813230800, {  }, $options?.signal),
    },
  } as const;
}
