<Project>
  <Import Project="../Directory.Build.props" />

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('Tests'))">
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup Condition="$(MSBuildProjectName.EndsWith('Tests'))">
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="AwesomeAssertions.Analyzers" PrivateAssets="all" />
    <PackageReference Include="xunit.v3.mtp-v2" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
