<Project>
  <Import Project="../../../Directory.Build.props" />

  <PropertyGroup>
    <BaseIntermediateOutputPath>obj\</BaseIntermediateOutputPath>
    <BaseOutputPath>bin\</BaseOutputPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(MSBuildProjectDirectory)\bin\**;$(MSBuildProjectDirectory)\obj\**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
