using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

using Microsoft.CodeAnalysis.CSharp;

namespace Nanto.Sdk.Capabilities;

internal static class NantoCapabilityCompiler
{
    internal const int MaximumDocumentBytes = 256 * 1024;
    private const int MaximumIdentifierLength = 128;
    private const int MaximumOriginLength = 2048;
    private static readonly UTF8Encoding _strictUtf8 = new(false, true);

    public static NantoCompiledCapabilityPolicy Compile(
        IEnumerable<NantoCapabilityInput> inputs,
        IEnumerable<NantoCapabilityPermissionCatalogEntry> permissionCatalog)
    {
        ArgumentNullException.ThrowIfNull(inputs);
        ArgumentNullException.ThrowIfNull(permissionCatalog);
        NantoCapabilityPermissionCatalogEntry[] permissions = permissionCatalog.ToArray();
        if (permissions.GroupBy(static permission => permission.Identifier, StringComparer.Ordinal)
            .FirstOrDefault(static group => group.Count() > 1) is not null)
        {
            throw Error("NANTO4006", "permission-catalog", "$", "Permission identifier has more than one owner.");
        }

        var byPermission = permissions.ToDictionary(static permission => permission.Identifier, StringComparer.Ordinal);
        var documentIdentifiers = new HashSet<string>(StringComparer.Ordinal);
        var grantKeys = new HashSet<(string Window, string Origin, string Permission)>();
        var entries = new List<NantoCompiledCapabilityEntry>();

        foreach (NantoCapabilityInput input in inputs.OrderBy(static input => input.DisplayPath, StringComparer.Ordinal))
        {
            ParsedCapabilityDocument document = Parse(input, byPermission);
            if (!documentIdentifiers.Add(document.Identifier))
            {
                throw Error("NANTO4004", input.DisplayPath, "$.identifier", "Capability document identifier is duplicated.");
            }

            foreach (string window in document.Windows)
            {
                foreach (string origin in document.Origins)
                {
                    foreach (ParsedGrant grant in document.Grants)
                    {
                        if (!grantKeys.Add((window, origin, grant.Permission.Identifier)))
                        {
                            throw Error(
                                "NANTO4007",
                                input.DisplayPath,
                                "$.permissions",
                                "A permission grant is duplicated for the same window and origin.");
                        }

                        entries.Add(new NantoCompiledCapabilityEntry
                        {
                            Window = window,
                            Origin = origin,
                            Permission = grant.Permission.Identifier,
                            Members = grant.Permission.Members,
                            MemberIds = grant.Permission.MemberIds,
                            ScopeJson = grant.ScopeJson,
                            ScopeSha256 = grant.ScopeJson is null ? null : Hash(Encoding.UTF8.GetBytes(grant.ScopeJson)),
                        });
                    }
                }
            }
        }

        NantoCompiledCapabilityEntry[] ordered = entries
            .OrderBy(static entry => entry.Window, StringComparer.Ordinal)
            .ThenBy(static entry => entry.Origin, StringComparer.Ordinal)
            .ThenBy(static entry => entry.Permission, StringComparer.Ordinal)
            .ToArray();
        return new NantoCompiledCapabilityPolicy
        {
            Fingerprint = Hash(CanonicalizePolicy(ordered)),
            Entries = ordered,
        };
    }

    public static string EmitSource(NantoCompiledCapabilityPolicy policy)
    {
        ArgumentNullException.ThrowIfNull(policy);
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace Nanto.Generated;");
        builder.AppendLine();
        builder.AppendLine("internal static class NantoGeneratedCapabilityPolicy");
        builder.AppendLine("{");
        builder.Append("    internal const string Fingerprint = ").Append(SymbolDisplay.FormatLiteral(policy.Fingerprint, true)).AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("    internal static readonly Entry[] Entries =");
        builder.AppendLine("        [");
        foreach (NantoCompiledCapabilityEntry entry in policy.Entries)
        {
            builder.Append("            new(")
                .Append(SymbolDisplay.FormatLiteral(entry.Window, true)).Append(", ")
                .Append(SymbolDisplay.FormatLiteral(entry.Origin, true)).Append(", ")
                .Append(SymbolDisplay.FormatLiteral(entry.Permission, true)).Append(", [")
                .Append(string.Join(", ", entry.Members.Select(static member => SymbolDisplay.FormatLiteral(member, true))))
                .Append("], [")
                .Append(string.Join(", ", entry.MemberIds.Select(static id => id.ToString(CultureInfo.InvariantCulture) + "U")))
                .Append("], ")
                .Append(entry.ScopeJson is null ? "null" : SymbolDisplay.FormatLiteral(entry.ScopeJson, true))
                .AppendLine("),");
        }

        builder.AppendLine("        ];");
        builder.AppendLine();
        builder.AppendLine("    internal readonly record struct Entry(");
        builder.AppendLine("        string Window,");
        builder.AppendLine("        string Origin,");
        builder.AppendLine("        string Permission,");
        builder.AppendLine("        string[] Members,");
        builder.AppendLine("        uint[] MemberIds,");
        builder.AppendLine("        string? ScopeJson);");
        builder.AppendLine("}");
        return builder.ToString();
    }

    public static string SerializeInspection(NantoCompiledCapabilityPolicy policy)
    {
        ArgumentNullException.ThrowIfNull(policy);
        var inspection = new NantoCapabilityInspectionDocument
        {
            Fingerprint = policy.Fingerprint,
            Entries = policy.Entries.Select(static entry => new NantoCapabilityInspectionEntry
            {
                Window = entry.Window,
                Origin = entry.Origin,
                Permission = entry.Permission,
                Members = entry.Members,
                MemberIds = entry.MemberIds,
                ScopeSha256 = entry.ScopeSha256,
            }).ToArray(),
        };
        return JsonSerializer.Serialize(inspection, NantoCapabilityInspectionJsonContext.Default.NantoCapabilityInspectionDocument);
    }

    private static ParsedCapabilityDocument Parse(
        NantoCapabilityInput input,
        IReadOnlyDictionary<string, NantoCapabilityPermissionCatalogEntry> permissionCatalog)
    {
        byte[] bytes = ReadDocument(input);
        try
        {
            string text = _strictUtf8.GetString(bytes);
            if (text.Length > 0 && text[0] == '\uFEFF')
            {
                throw Error("NANTO4001", input.DisplayPath, "$", "Capability document must be UTF-8 without a byte-order mark.");
            }
        }
        catch (DecoderFallbackException)
        {
            throw Error("NANTO4001", input.DisplayPath, "$", "Capability document is not valid UTF-8.");
        }

        try
        {
            using JsonDocument json = JsonDocument.Parse(bytes, new JsonDocumentOptions { MaxDepth = 32 });
            JsonElement root = json.RootElement;
            RequireObject(
                root,
                input.DisplayPath,
                "$",
                ["schemaVersion", "identifier", "windows", "origins", "permissions"],
                ["$schema"]);
            if (root.TryGetProperty("$schema", out JsonElement schema)
                && (schema.ValueKind != JsonValueKind.String
                    || schema.GetString() != "https://nanto.dev/schemas/capability/v1.json"))
            {
                throw Error("NANTO4003", input.DisplayPath, "$.$schema", "Capability schema identifier is not supported.");
            }

            RequireInteger(root.GetProperty("schemaVersion"), input.DisplayPath, "$.schemaVersion", 1);
            string identifier = RequireString(root.GetProperty("identifier"), input.DisplayPath, "$.identifier", MaximumIdentifierLength);
            if (!IsDocumentIdentifier(identifier))
            {
                throw Error("NANTO4003", input.DisplayPath, "$.identifier", "Capability identifier must be lowercase ASCII kebab-case.");
            }

            string[] windows = ReadUniqueStrings(
                root.GetProperty("windows"),
                input.DisplayPath,
                "$.windows",
                static value => value == "main",
                MaximumIdentifierLength,
                normalize: null);
            string[] origins = ReadUniqueStrings(
                root.GetProperty("origins"),
                input.DisplayPath,
                "$.origins",
                static _ => true,
                MaximumOriginLength,
                value => NormalizeOrigin(value, input.DisplayPath));
            ParsedGrant[] grants = ParseGrants(root.GetProperty("permissions"), input, permissionCatalog);
            return new ParsedCapabilityDocument(identifier, windows, origins, grants);
        }
        catch (JsonException exception)
        {
            throw Error(
                "NANTO4002",
                input.DisplayPath,
                "$",
                $"Capability document is malformed JSON at line {exception.LineNumber ?? 0}, byte {exception.BytePositionInLine ?? 0}.");
        }
    }

    private static ParsedGrant[] ParseGrants(
        JsonElement element,
        NantoCapabilityInput input,
        IReadOnlyDictionary<string, NantoCapabilityPermissionCatalogEntry> permissionCatalog)
    {
        if (element.ValueKind != JsonValueKind.Array || element.GetArrayLength() == 0)
        {
            throw Error("NANTO4003", input.DisplayPath, "$.permissions", "Permissions must be a non-empty array.");
        }

        var identifiers = new HashSet<string>(StringComparer.Ordinal);
        var grants = new List<ParsedGrant>();
        var index = 0;
        foreach (JsonElement elementGrant in element.EnumerateArray())
        {
            string path = $"$.permissions[{index}]";
            string identifier;
            JsonElement? scope = null;
            if (elementGrant.ValueKind == JsonValueKind.String)
            {
                identifier = RequireString(elementGrant, input.DisplayPath, path, MaximumIdentifierLength);
            }
            else
            {
                RequireObject(elementGrant, input.DisplayPath, path, ["identifier", "scope"], []);
                identifier = RequireString(elementGrant.GetProperty("identifier"), input.DisplayPath, path + ".identifier", MaximumIdentifierLength);
                scope = elementGrant.GetProperty("scope");
            }

            if (!identifiers.Add(identifier))
            {
                throw Error("NANTO4007", input.DisplayPath, path, "Permission is duplicated in the capability document.");
            }

            if (!permissionCatalog.TryGetValue(identifier, out NantoCapabilityPermissionCatalogEntry? permission))
            {
                throw Error("NANTO4006", input.DisplayPath, path, "Capability references an unknown permission.");
            }

            string? scopeJson = null;
            if (permission.ScopeSchemaPath is null)
            {
                if (scope is not null)
                {
                    throw Error("NANTO4008", input.DisplayPath, path + ".scope", "Unscoped permission must not declare a scope.");
                }
            }
            else
            {
                if (scope is null)
                {
                    throw Error("NANTO4008", input.DisplayPath, path, "Scoped permission requires a scope.");
                }

                ValidateScope(scope.Value, permission, input.DisplayPath, path + ".scope");
                scopeJson = CanonicalizeJson(scope.Value);
            }

            grants.Add(new ParsedGrant(permission, scopeJson));
            index++;
        }

        return [.. grants.OrderBy(static grant => grant.Permission.Identifier, StringComparer.Ordinal)];
    }

    private static void ValidateScope(
        JsonElement scope,
        NantoCapabilityPermissionCatalogEntry permission,
        string document,
        string propertyPath)
    {
        byte[] schemaBytes = ReadStableFile(permission.ScopeSchemaPath!, document, propertyPath, MaximumDocumentBytes);
        string actualHash = Hash(schemaBytes);
        if (!string.Equals(actualHash, permission.ScopeSchemaSha256, StringComparison.Ordinal))
        {
            throw Error("NANTO4009", document, propertyPath, "Plugin scope schema content does not match its manifest hash.");
        }

        try
        {
            string schemaText = _strictUtf8.GetString(schemaBytes);
            if (schemaText.Length > 0 && schemaText[0] == '\uFEFF')
            {
                throw Error("NANTO4009", document, propertyPath, "Plugin scope schema must be UTF-8 without a byte-order mark.");
            }

            using JsonDocument schema = JsonDocument.Parse(schemaBytes, new JsonDocumentOptions { MaxDepth = 32 });
            ValidateSchemaNode(schema.RootElement, document, propertyPath);
            ValidateInstance(scope, schema.RootElement, document, propertyPath);
        }
        catch (DecoderFallbackException)
        {
            throw Error("NANTO4009", document, propertyPath, "Plugin scope schema is not valid UTF-8.");
        }
        catch (JsonException)
        {
            throw Error("NANTO4009", document, propertyPath, "Plugin scope schema is malformed JSON.");
        }
    }

    private static void ValidateSchemaNode(JsonElement schema, string document, string propertyPath)
    {
        if (schema.ValueKind != JsonValueKind.Object)
        {
            throw Error("NANTO4009", document, propertyPath, "Plugin scope schema must be a JSON object.");
        }

        string[] allowed =
        [
            "$schema", "$id", "title", "description", "type", "additionalProperties", "required", "properties", "items",
            "minLength", "maxLength", "minItems", "maxItems", "minimum", "maximum", "pattern", "enum", "const",
        ];
        var allowedProperties = allowed.ToHashSet(StringComparer.Ordinal);
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (JsonProperty property in schema.EnumerateObject())
        {
            if (!seen.Add(property.Name) || !allowedProperties.Contains(property.Name))
            {
                throw Error("NANTO4009", document, propertyPath, "Plugin scope schema uses an unsupported keyword.");
            }
        }

        if (schema.TryGetProperty("type", out JsonElement type)
            && (type.ValueKind != JsonValueKind.String
                || type.GetString() is not ("object" or "array" or "string" or "number" or "integer" or "boolean" or "null")))
        {
            throw Error("NANTO4009", document, propertyPath, "Plugin scope schema has an unsupported type.");
        }

        if (schema.TryGetProperty("additionalProperties", out JsonElement additionalProperties)
            && additionalProperties.ValueKind is not (JsonValueKind.True or JsonValueKind.False))
        {
            throw Error("NANTO4009", document, propertyPath, "Plugin scope schema additionalProperties must be Boolean.");
        }

        if (schema.TryGetProperty("required", out JsonElement required))
        {
            var names = new HashSet<string>(StringComparer.Ordinal);
            if (required.ValueKind != JsonValueKind.Array
                || required.EnumerateArray().Any(item => item.ValueKind != JsonValueKind.String || item.GetString() is not { } name || !names.Add(name)))
            {
                throw Error("NANTO4009", document, propertyPath, "Plugin scope schema required must contain unique strings.");
            }
        }

        foreach (string limitName in new[] { "minLength", "maxLength", "minItems", "maxItems" })
        {
            if (schema.TryGetProperty(limitName, out JsonElement limit) && (!limit.TryGetInt32(out int limitValue) || limitValue < 0))
            {
                throw Error("NANTO4009", document, propertyPath, "Plugin scope schema length limit is invalid.");
            }
        }

        foreach (string numberName in new[] { "minimum", "maximum" })
        {
            if (schema.TryGetProperty(numberName, out JsonElement number) && number.ValueKind != JsonValueKind.Number)
            {
                throw Error("NANTO4009", document, propertyPath, "Plugin scope schema numeric limit is invalid.");
            }
        }

        if (schema.TryGetProperty("pattern", out JsonElement pattern) && pattern.ValueKind != JsonValueKind.String)
        {
            throw Error("NANTO4009", document, propertyPath, "Plugin scope schema pattern is invalid.");
        }

        if (schema.TryGetProperty("enum", out JsonElement enumeration)
            && (enumeration.ValueKind != JsonValueKind.Array || enumeration.GetArrayLength() == 0))
        {
            throw Error("NANTO4009", document, propertyPath, "Plugin scope schema enumeration must be a non-empty array.");
        }

        if (schema.TryGetProperty("properties", out JsonElement properties))
        {
            if (properties.ValueKind != JsonValueKind.Object)
            {
                throw Error("NANTO4009", document, propertyPath, "Plugin scope schema properties must be an object.");
            }

            var propertyNames = new HashSet<string>(StringComparer.Ordinal);
            foreach (JsonProperty property in properties.EnumerateObject())
            {
                if (!propertyNames.Add(property.Name))
                {
                    throw Error("NANTO4009", document, propertyPath, "Plugin scope schema property is duplicated.");
                }

                ValidateSchemaNode(property.Value, document, propertyPath);
            }
        }

        if (schema.TryGetProperty("items", out JsonElement items))
        {
            ValidateSchemaNode(items, document, propertyPath);
        }
    }

    private static void ValidateInstance(JsonElement value, JsonElement schema, string document, string propertyPath)
    {
        if (schema.TryGetProperty("type", out JsonElement type) && !MatchesType(value, type.GetString()!))
        {
            throw Error("NANTO4009", document, propertyPath, "Scope does not match the plugin schema type.");
        }

        if (schema.TryGetProperty("const", out JsonElement constant) && CanonicalizeJson(value) != CanonicalizeJson(constant))
        {
            throw Error("NANTO4009", document, propertyPath, "Scope does not match the plugin schema constant.");
        }

        if (schema.TryGetProperty("enum", out JsonElement values)
            && (values.ValueKind != JsonValueKind.Array
                || !values.EnumerateArray().Any(candidate => CanonicalizeJson(candidate) == CanonicalizeJson(value))))
        {
            throw Error("NANTO4009", document, propertyPath, "Scope does not match the plugin schema enumeration.");
        }

        if (value.ValueKind == JsonValueKind.Object)
        {
            ValidateObject(value, schema, document, propertyPath);
        }
        else if (value.ValueKind == JsonValueKind.Array)
        {
            ValidateArray(value, schema, document, propertyPath);
        }
        else if (value.ValueKind == JsonValueKind.String)
        {
            ValidateString(value.GetString()!, schema, document, propertyPath);
        }
        else if (value.ValueKind == JsonValueKind.Number)
        {
            ValidateNumber(value, schema, document, propertyPath);
        }
    }

    private static void ValidateObject(JsonElement value, JsonElement schema, string document, string propertyPath)
    {
        var required = new HashSet<string>(StringComparer.Ordinal);
        if (schema.TryGetProperty("required", out JsonElement requiredElement))
        {
            if (requiredElement.ValueKind != JsonValueKind.Array)
            {
                throw Error("NANTO4009", document, propertyPath, "Plugin scope schema required must be an array.");
            }

            foreach (JsonElement item in requiredElement.EnumerateArray())
            {
                if (item.ValueKind != JsonValueKind.String || item.GetString() is not { } name || !required.Add(name))
                {
                    throw Error("NANTO4009", document, propertyPath, "Plugin scope schema required entry is invalid.");
                }
            }
        }

        JsonElement properties = default;
        bool hasProperties = schema.TryGetProperty("properties", out properties);
        bool rejectAdditional = schema.TryGetProperty("additionalProperties", out JsonElement additional)
            && additional.ValueKind == JsonValueKind.False;
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (JsonProperty property in value.EnumerateObject())
        {
            if (!seen.Add(property.Name))
            {
                throw Error("NANTO4009", document, propertyPath + "." + property.Name, "Scope property is duplicated.");
            }

            if (hasProperties && properties.TryGetProperty(property.Name, out JsonElement propertySchema))
            {
                ValidateInstance(property.Value, propertySchema, document, propertyPath + "." + property.Name);
            }
            else if (rejectAdditional)
            {
                throw Error("NANTO4009", document, propertyPath + "." + property.Name, "Scope property is not allowed by the plugin schema.");
            }

            required.Remove(property.Name);
        }

        if (required.Count > 0)
        {
            throw Error("NANTO4009", document, propertyPath, "Scope is missing a property required by the plugin schema.");
        }
    }

    private static void ValidateArray(JsonElement value, JsonElement schema, string document, string propertyPath)
    {
        int length = value.GetArrayLength();
        ValidateIntegerLimit(schema, "minItems", length, static (actual, limit) => actual >= limit, document, propertyPath);
        ValidateIntegerLimit(schema, "maxItems", length, static (actual, limit) => actual <= limit, document, propertyPath);
        if (schema.TryGetProperty("items", out JsonElement itemSchema))
        {
            var index = 0;
            foreach (JsonElement item in value.EnumerateArray())
            {
                ValidateInstance(item, itemSchema, document, $"{propertyPath}[{index}]");
                index++;
            }
        }
    }

    private static void ValidateString(string value, JsonElement schema, string document, string propertyPath)
    {
        ValidateIntegerLimit(schema, "minLength", value.Length, static (actual, limit) => actual >= limit, document, propertyPath);
        ValidateIntegerLimit(schema, "maxLength", value.Length, static (actual, limit) => actual <= limit, document, propertyPath);
        if (schema.TryGetProperty("pattern", out JsonElement pattern))
        {
            if (pattern.ValueKind != JsonValueKind.String || pattern.GetString() is not { } expression)
            {
                throw Error("NANTO4009", document, propertyPath, "Plugin scope schema pattern is invalid.");
            }

            try
            {
                if (!Regex.IsMatch(value, expression, RegexOptions.CultureInvariant, TimeSpan.FromMilliseconds(100)))
                {
                    throw Error("NANTO4009", document, propertyPath, "Scope string does not match the plugin schema pattern.");
                }
            }
            catch (ArgumentException)
            {
                throw Error("NANTO4009", document, propertyPath, "Plugin scope schema pattern is invalid.");
            }
            catch (RegexMatchTimeoutException)
            {
                throw Error("NANTO4009", document, propertyPath, "Plugin scope schema pattern exceeded its validation budget.");
            }
        }
    }

    private static void ValidateNumber(JsonElement value, JsonElement schema, string document, string propertyPath)
    {
        if (!value.TryGetDecimal(out decimal number))
        {
            throw Error("NANTO4009", document, propertyPath, "Scope number is outside the supported decimal range.");
        }

        if (schema.TryGetProperty("minimum", out JsonElement minimum)
            && (!minimum.TryGetDecimal(out decimal minimumValue) || number < minimumValue))
        {
            throw Error("NANTO4009", document, propertyPath, "Scope number is below the plugin schema minimum.");
        }

        if (schema.TryGetProperty("maximum", out JsonElement maximum)
            && (!maximum.TryGetDecimal(out decimal maximumValue) || number > maximumValue))
        {
            throw Error("NANTO4009", document, propertyPath, "Scope number is above the plugin schema maximum.");
        }
    }

    private static void ValidateIntegerLimit(
        JsonElement schema,
        string name,
        int actual,
        Func<int, int, bool> predicate,
        string document,
        string propertyPath)
    {
        if (!schema.TryGetProperty(name, out JsonElement limit))
        {
            return;
        }

        if (!limit.TryGetInt32(out int value) || value < 0)
        {
            throw Error("NANTO4009", document, propertyPath, "Plugin scope schema length limit is invalid.");
        }

        if (!predicate(actual, value))
        {
            throw Error("NANTO4009", document, propertyPath, "Scope length does not satisfy the plugin schema.");
        }
    }

    private static bool MatchesType(JsonElement value, string type) => type switch
    {
        "object" => value.ValueKind == JsonValueKind.Object,
        "array" => value.ValueKind == JsonValueKind.Array,
        "string" => value.ValueKind == JsonValueKind.String,
        "number" => value.ValueKind == JsonValueKind.Number,
        "integer" => value.ValueKind == JsonValueKind.Number && value.TryGetInt64(out _),
        "boolean" => value.ValueKind is JsonValueKind.True or JsonValueKind.False,
        "null" => value.ValueKind == JsonValueKind.Null,
        _ => false,
    };

    private static string[] ReadUniqueStrings(
        JsonElement element,
        string document,
        string propertyPath,
        Func<string, bool> validator,
        int maximumLength,
        Func<string, string>? normalize)
    {
        if (element.ValueKind != JsonValueKind.Array || element.GetArrayLength() == 0)
        {
            throw Error("NANTO4003", document, propertyPath, "Property must be a non-empty array.");
        }

        var values = new HashSet<string>(StringComparer.Ordinal);
        var index = 0;
        foreach (JsonElement item in element.EnumerateArray())
        {
            string value = RequireString(item, document, $"{propertyPath}[{index}]", maximumLength);
            if (!validator(value))
            {
                throw Error("NANTO4003", document, $"{propertyPath}[{index}]", "Array item is invalid.");
            }

            value = normalize is null ? value : normalize(value);
            if (!values.Add(value))
            {
                throw Error("NANTO4003", document, $"{propertyPath}[{index}]", "Array item is duplicated after normalization.");
            }

            index++;
        }

        return [.. values.Order(StringComparer.Ordinal)];
    }

    private static string NormalizeOrigin(string value, string document)
    {
        if (value == "local")
        {
            return value;
        }

        if (!Uri.TryCreate(value, UriKind.Absolute, out Uri? uri)
            || !uri.IsWellFormedOriginalString()
            || !uri.Scheme.Equals(Uri.UriSchemeHttps, StringComparison.OrdinalIgnoreCase)
            || uri.UserInfo.Length != 0
            || uri.Query.Length != 0
            || uri.Fragment.Length != 0
            || uri.AbsolutePath != "/"
            || uri.HostNameType == UriHostNameType.Unknown)
        {
            throw Error("NANTO4005", document, "$.origins", "Origin must be 'local' or an exact HTTPS origin.");
        }

        string host;
        try
        {
            host = uri.HostNameType == UriHostNameType.IPv6
                ? "[" + uri.IdnHost.ToLowerInvariant() + "]"
                : new IdnMapping().GetAscii(uri.IdnHost).ToLowerInvariant();
        }
        catch (ArgumentException)
        {
            throw Error("NANTO4005", document, "$.origins", "Origin host is invalid.");
        }

        if (host.Length == 0 || host.Contains('*', StringComparison.Ordinal))
        {
            throw Error("NANTO4005", document, "$.origins", "Origin host is invalid.");
        }

        return "https://" + host + (uri.IsDefaultPort ? string.Empty : ":" + uri.Port.ToString(CultureInfo.InvariantCulture));
    }

    private static byte[] ReadDocument(NantoCapabilityInput input)
    {
        try
        {
            var file = new FileInfo(input.Path);
            if (!file.Exists || file.Length is <= 0 or > MaximumDocumentBytes)
            {
                throw Error("NANTO4000", input.DisplayPath, "$", $"Capability document must contain between 1 and {MaximumDocumentBytes} bytes.");
            }

            return ReadStableFile(file.FullName, input.DisplayPath, "$", MaximumDocumentBytes);
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
        {
            _ = exception;
            throw Error("NANTO4000", input.DisplayPath, "$", "Capability document could not be read.");
        }
    }

    private static byte[] ReadStableFile(string path, string document, string propertyPath, long maximumBytes)
    {
        try
        {
            var file = new FileInfo(path);
            long length = file.Length;
            DateTime writeTime = file.LastWriteTimeUtc;
            if (length > maximumBytes)
            {
                throw Error("NANTO4009", document, propertyPath, "Plugin scope schema exceeds the size limit.");
            }

            byte[] bytes = File.ReadAllBytes(path);
            file.Refresh();
            if (bytes.LongLength != length || file.Length != length || file.LastWriteTimeUtc != writeTime)
            {
                throw Error("NANTO4000", document, propertyPath, "Capability input changed while it was inspected.");
            }

            return bytes;
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
        {
            _ = exception;
            throw Error("NANTO4000", document, propertyPath, "Capability input could not be read.");
        }
    }

    private static void RequireObject(JsonElement element, string document, string propertyPath, string[] required, string[] optional)
    {
        if (element.ValueKind != JsonValueKind.Object)
        {
            throw Error("NANTO4003", document, propertyPath, "Expected a JSON object.");
        }

        var allowed = required.Concat(optional).ToHashSet(StringComparer.Ordinal);
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (JsonProperty property in element.EnumerateObject())
        {
            if (!allowed.Contains(property.Name))
            {
                throw Error("NANTO4003", document, propertyPath + "." + property.Name, "Unknown capability property.");
            }

            if (!seen.Add(property.Name))
            {
                throw Error("NANTO4003", document, propertyPath + "." + property.Name, "Duplicate capability property.");
            }
        }

        string? missing = required.FirstOrDefault(property => !seen.Contains(property));
        if (missing is not null)
        {
            throw Error("NANTO4003", document, propertyPath + "." + missing, "Required capability property is missing.");
        }
    }

    private static string RequireString(JsonElement element, string document, string propertyPath, int maximumLength)
    {
        if (element.ValueKind != JsonValueKind.String
            || element.GetString() is not { Length: > 0 } value
            || value.Length > maximumLength)
        {
            throw Error("NANTO4003", document, propertyPath, $"Property must be a non-empty string no longer than {maximumLength} characters.");
        }

        return value;
    }

    private static void RequireInteger(JsonElement element, string document, string propertyPath, int expected)
    {
        if (element.ValueKind != JsonValueKind.Number || !element.TryGetInt32(out int value) || value != expected)
        {
            throw Error("NANTO4003", document, propertyPath, $"Property must equal {expected}.");
        }
    }

    private static bool IsDocumentIdentifier(string value) => value.Length > 0
        && value[0] is >= 'a' and <= 'z'
        && value.Split('-').All(static segment => segment.Length > 0
            && segment.All(static character => character is >= 'a' and <= 'z' || char.IsAsciiDigit(character)));

    private static byte[] CanonicalizePolicy(IEnumerable<NantoCompiledCapabilityEntry> entries)
    {
        var builder = new StringBuilder("v1\n");
        foreach (NantoCompiledCapabilityEntry entry in entries)
        {
            builder.Append(entry.Window).Append('|').Append(entry.Origin).Append('|').Append(entry.Permission).Append('\n');
            foreach (string member in entry.Members)
            {
                builder.Append("member=").Append(member).Append('\n');
            }

            foreach (uint memberId in entry.MemberIds)
            {
                builder.Append("member-id=").Append(memberId.ToString(CultureInfo.InvariantCulture)).Append('\n');
            }

            if (entry.ScopeJson is not null)
            {
                builder.Append("scope=").Append(entry.ScopeJson).Append('\n');
            }
        }

        return Encoding.UTF8.GetBytes(builder.ToString());
    }

    private static string CanonicalizeJson(JsonElement value)
    {
        using var stream = new MemoryStream();
        using (var writer = new Utf8JsonWriter(stream))
        {
            WriteCanonicalJson(writer, value);
        }

        return Encoding.UTF8.GetString(stream.ToArray());
    }

    private static void WriteCanonicalJson(Utf8JsonWriter writer, JsonElement value)
    {
        switch (value.ValueKind)
        {
            case JsonValueKind.Object:
                writer.WriteStartObject();
                foreach (JsonProperty property in value.EnumerateObject().OrderBy(static property => property.Name, StringComparer.Ordinal))
                {
                    writer.WritePropertyName(property.Name);
                    WriteCanonicalJson(writer, property.Value);
                }

                writer.WriteEndObject();
                break;
            case JsonValueKind.Array:
                writer.WriteStartArray();
                foreach (JsonElement item in value.EnumerateArray())
                {
                    WriteCanonicalJson(writer, item);
                }

                writer.WriteEndArray();
                break;
            case JsonValueKind.Number:
                if (value.TryGetDecimal(out decimal number))
                {
                    writer.WriteNumberValue(number);
                }
                else
                {
                    writer.WriteRawValue(value.GetRawText(), skipInputValidation: true);
                }

                break;
            default:
                value.WriteTo(writer);
                break;
        }
    }

    private static string Hash(ReadOnlySpan<byte> bytes) => Convert.ToHexString(SHA256.HashData(bytes));

    private static NantoCapabilityException Error(string code, string document, string propertyPath, string message) =>
        new(code, document, propertyPath, message);

    private sealed record ParsedCapabilityDocument(string Identifier, string[] Windows, string[] Origins, ParsedGrant[] Grants);

    private sealed record ParsedGrant(NantoCapabilityPermissionCatalogEntry Permission, string? ScopeJson);
}
