<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Nanto.Core/Nanto.Core.csproj" />
    <ProjectReference Include="../../src/Nanto.Generators/Nanto.Generators.csproj" />
    <ProjectReference Include="../../src/Nanto.Sdk/Nanto.Sdk.csproj" />
    <ProjectReference Include="../Nanto.Sdk.AssetFixture/Nanto.Sdk.AssetFixture.csproj" />
  </ItemGroup>
</Project>
