using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace Nanto.WebView2InteropGen;

public static partial class Generator
{
    private const int GeneratorFormatVersion = 1;
    private const string HeaderRelativePath = "build/native/include/WebView2.h";
    private const string IdlRelativePath = "WebView2.idl";
    private const string ManifestFileName = "webview2-interop-manifest.json";
    private const string SourceFileName = "WebView2Interop.g.cs";

    public static void Generate(string packageRoot, string specPath, string outputDirectory)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(packageRoot);
        ArgumentException.ThrowIfNullOrWhiteSpace(specPath);
        ArgumentException.ThrowIfNullOrWhiteSpace(outputDirectory);

        packageRoot = Path.GetFullPath(packageRoot);
        specPath = Path.GetFullPath(specPath);
        outputDirectory = Path.GetFullPath(outputDirectory);
        var idlPath = Path.Combine(packageRoot, IdlRelativePath);
        var headerPath = Path.Combine(packageRoot, HeaderRelativePath.Replace('/', Path.DirectorySeparatorChar));
        ThrowIfMissing(idlPath, "WebView2 IDL");
        ThrowIfMissing(headerPath, "WebView2 native header");
        ThrowIfMissing(specPath, "projection specification");

        var specBytes = File.ReadAllBytes(specPath);
        var specification = JsonSerializer.Deserialize(specBytes, GeneratorJsonContext.Default.InteropSpecification)
            ?? throw new InvalidDataException("The projection specification is empty.");
        ValidateSpecification(specification);

        var idlBytes = File.ReadAllBytes(idlPath);
        var headerBytes = File.ReadAllBytes(headerPath);
        var packageVersion = GetPackageVersion(packageRoot);
        var idlModel = ParseIdl(Encoding.UTF8.GetString(idlBytes));
        var headerModel = ParseHeader(Encoding.UTF8.GetString(headerBytes));
        var projection = ResolveProjection(specification, idlModel, headerModel);
        var source = EmitSource(specification.Namespace, projection, idlModel.Enums, specification.Types);
        var sourceBytes = Utf8(source);
        var manifest = EmitManifest(specification, projection, packageVersion, idlBytes, headerBytes, specBytes, sourceBytes);

        Directory.CreateDirectory(outputDirectory);
        File.WriteAllBytes(Path.Combine(outputDirectory, SourceFileName), sourceBytes);
        File.WriteAllBytes(Path.Combine(outputDirectory, ManifestFileName), Utf8(manifest));
    }

    private static string EmitManifest(
        InteropSpecification specification,
        IReadOnlyList<ProjectedInterface> projection,
        string packageVersion,
        byte[] idlBytes,
        byte[] headerBytes,
        byte[] specBytes,
        byte[] sourceBytes)
    {
        var manifest = new InteropManifest
        {
            SchemaVersion = 1,
            GeneratorFormatVersion = GeneratorFormatVersion,
            PackageId = "Microsoft.Web.WebView2",
            PackageVersion = packageVersion,
            Inputs =
            [
                new ManifestFile { Path = IdlRelativePath, Sha256 = Hash(idlBytes) },
                new ManifestFile { Path = HeaderRelativePath, Sha256 = Hash(headerBytes) },
                new ManifestFile { Path = "eng/Nanto.WebView2InteropGen/webview2-interop-spec.json", Sha256 = Hash(specBytes) },
            ],
            Interfaces = projection.Select(static item => new ManifestInterface
            {
                Name = item.Interface.Name,
                Iid = item.Interface.Iid.ToLowerInvariant(),
                BaseInterface = item.Interface.BaseName,
                EmittedMethodCount = item.Methods.Count,
            }).ToArray(),
            Output = new ManifestOutput
            {
                Path = "src/Nanto.Hosting.Windows/Interop/Generated/WebView2Interop.g.cs",
                ByteLength = sourceBytes.Length,
                Sha256 = Hash(sourceBytes),
                Encoding = "utf-8",
                LineEndings = "lf",
            },
        };
        return JsonSerializer.Serialize(manifest, GeneratorJsonContext.Default.InteropManifest);
    }

    private static string EmitSource(
        string namespaceName,
        IReadOnlyList<ProjectedInterface> projection,
        IReadOnlyDictionary<string, IdlEnum> enums,
        IReadOnlyList<string> selectedTypes)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Update: dotnet build eng/Nanto.WebView2InteropGen/Nanto.WebView2InteropGen.csproj -c Release -t:UpdateWebView2Interop");
        builder.AppendLine("// Verify: dotnet test tests/Nanto.Hosting.Windows.InteropGeneration.IntegrationTests/Nanto.Hosting.Windows.InteropGeneration.IntegrationTests.csproj -p:TestScope=All");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System.Runtime.InteropServices;");
        builder.AppendLine("using System.Runtime.InteropServices.Marshalling;");
        builder.AppendLine();
        builder.Append("namespace ").Append(namespaceName).AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("[StructLayout(LayoutKind.Sequential)]");
        builder.AppendLine("internal readonly struct EventRegistrationToken(long value)");
        builder.AppendLine("{");
        builder.AppendLine("    public long Value { get; } = value;");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("[StructLayout(LayoutKind.Sequential)]");
        builder.AppendLine("internal readonly struct WebView2Rect(int left, int top, int right, int bottom)");
        builder.AppendLine("{");
        builder.AppendLine("    public int Left { get; } = left;");
        builder.AppendLine("    public int Top { get; } = top;");
        builder.AppendLine("    public int Right { get; } = right;");
        builder.AppendLine("    public int Bottom { get; } = bottom;");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("[StructLayout(LayoutKind.Sequential)]");
        builder.AppendLine("internal readonly struct WebView2Point(int x, int y)");
        builder.AppendLine("{");
        builder.AppendLine("    public int X { get; } = x;");
        builder.AppendLine("    public int Y { get; } = y;");
        builder.AppendLine("}");

        foreach (var typeName in selectedTypes.Where(static name => name.StartsWith("COREWEBVIEW2_", StringComparison.Ordinal)).Order())
        {
            if (!enums.TryGetValue(typeName, out var enumModel))
            {
                throw new InvalidDataException($"Selected enum '{typeName}' was not found in WebView2.idl.");
            }

            builder.AppendLine();
            builder.Append("internal enum ").Append(typeName).AppendLine();
            builder.AppendLine("{");
            foreach (var value in enumModel.Values)
            {
                builder.Append("    ").Append(value.Name).Append(" = ").Append(value.Value.ToString(CultureInfo.InvariantCulture)).AppendLine(",");
            }

            builder.AppendLine("}");
        }

        foreach (var item in projection)
        {
            builder.AppendLine();
            builder.AppendLine("[GeneratedComInterface]");
            builder.Append("[Guid(\"").Append(item.Interface.Iid.ToLowerInvariant()).AppendLine("\")]");
            builder.AppendLine("[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]");
            builder.Append("internal partial interface ").Append(item.Interface.Name);
            if (item.Interface.BaseName != "IUnknown")
            {
                builder.Append(" : ").Append(item.Interface.BaseName);
            }

            builder.AppendLine();
            builder.AppendLine("{");
            foreach (var method in item.Methods)
            {
                builder.AppendLine("    [PreserveSig]");
                builder.Append("    int ").Append(method.Name).Append('(');
                for (var index = 0; index < method.Parameters.Count; index++)
                {
                    if (index > 0)
                    {
                        builder.Append(", ");
                    }

                    var parameter = method.Parameters[index];
                    builder.Append(parameter.ManagedType).Append(' ').Append(parameter.Name);
                }

                builder.AppendLine(");");
            }

            builder.AppendLine("}");
        }

        builder.AppendLine();
        builder.AppendLine("internal static partial class WebView2Loader");
        builder.AppendLine("{");
        builder.AppendLine("    internal const string LibraryName = \"WebView2Loader\";");
        builder.AppendLine();
        builder.AppendLine("    [LibraryImport(LibraryName, StringMarshalling = StringMarshalling.Utf16)]");
        builder.AppendLine("    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvStdcall)])]");
        builder.AppendLine("    internal static partial int CreateCoreWebView2EnvironmentWithOptions(");
        builder.AppendLine("        string? browserExecutableFolder,");
        builder.AppendLine("        string userDataFolder,");
        builder.AppendLine("        nint environmentOptions,");
        builder.AppendLine("        nint environmentCreatedHandler);");
        builder.AppendLine("}");
        return Normalize(builder.ToString());
    }

    private static List<ProjectedInterface> ResolveProjection(
        InteropSpecification specification,
        IdlModel idl,
        Dictionary<string, HeaderInterface> header)
    {
        var selected = specification.Interfaces.ToDictionary(static item => item.Name, StringComparer.Ordinal);
        var fullInterfaces = new HashSet<string>(StringComparer.Ordinal);
        foreach (var selection in specification.Interfaces)
        {
            if (!idl.Interfaces.TryGetValue(selection.Name, out var model))
            {
                throw new InvalidDataException($"Selected interface '{selection.Name}' was not found in WebView2.idl.");
            }

            for (var baseName = model.BaseName; baseName != "IUnknown";)
            {
                if (!idl.Interfaces.TryGetValue(baseName, out var baseModel))
                {
                    throw new InvalidDataException($"Base interface '{baseName}' for '{model.Name}' was not found in WebView2.idl.");
                }

                fullInterfaces.Add(baseName);
                baseName = baseModel.BaseName;
            }
        }

        var included = new HashSet<string>(selected.Keys, StringComparer.Ordinal);
        included.UnionWith(fullInterfaces);
        var ordered = TopologicalOrder(included, idl.Interfaces);
        var result = new List<ProjectedInterface>();
        foreach (var name in ordered)
        {
            var model = idl.Interfaces[name];
            IReadOnlyList<IdlMethod> methods;
            if (fullInterfaces.Contains(name) && !selected.ContainsKey(name))
            {
                methods = model.Methods;
            }
            else if (fullInterfaces.Contains(name))
            {
                methods = model.Methods;
            }
            else
            {
                var requested = selected[name].Methods;
                var missing = requested.Where(requestedName => model.Methods.All(method => method.Name != requestedName)).ToArray();
                if (missing.Length > 0)
                {
                    throw new InvalidDataException($"Interface '{name}' does not contain selected method(s): {string.Join(", ", missing)}.");
                }

                var lastIndex = model.Methods.FindLastIndex(method => requested.Contains(method.Name, StringComparer.Ordinal));
                methods = model.Methods.Take(lastIndex + 1).ToArray();
            }

            if (!header.TryGetValue(name, out var headerInterface))
            {
                throw new InvalidDataException($"Projected interface '{name}' was not found in WebView2.h.");
            }

            if (!string.Equals(model.Iid, headerInterface.Iid, StringComparison.OrdinalIgnoreCase)
                || !string.Equals(model.BaseName, headerInterface.BaseName, StringComparison.Ordinal)
                || !methods.Select(CreateNativeSignature)
                    .SequenceEqual(headerInterface.Methods.Take(methods.Count).Select(CreateNativeSignature), StringComparer.Ordinal))
            {
                throw new InvalidDataException($"WebView2 IDL/header ABI disagreement for interface '{name}'.");
            }

            result.Add(new ProjectedInterface(model, methods));
        }

        return result;
    }

    private static List<string> TopologicalOrder(
        HashSet<string> included,
        IReadOnlyDictionary<string, IdlInterface> interfaces)
    {
        var result = new List<string>();
        var visited = new HashSet<string>(StringComparer.Ordinal);
        foreach (var name in included.Order(StringComparer.Ordinal))
        {
            Visit(name);
        }

        return result;

        void Visit(string name)
        {
            if (!visited.Add(name))
            {
                return;
            }

            var baseName = interfaces[name].BaseName;
            if (baseName != "IUnknown" && included.Contains(baseName))
            {
                Visit(baseName);
            }

            result.Add(name);
        }
    }

    private static IdlModel ParseIdl(string text)
    {
        text = RemoveComments(text);
        var interfaces = new Dictionary<string, IdlInterface>(StringComparer.Ordinal);
        foreach (Match match in IdlInterfaceStartRegex().Matches(text))
        {
            var body = ReadBalancedBody(text, match.Index + match.Length - 1);
            var methods = ParseIdlMethods(body);
            var model = new IdlInterface(match.Groups["name"].Value, match.Groups["base"].Value, match.Groups["iid"].Value, methods);
            interfaces.TryAdd(model.Name, model);
        }

        var enums = new Dictionary<string, IdlEnum>(StringComparer.Ordinal);
        foreach (Match match in IdlEnumStartRegex().Matches(text))
        {
            var body = ReadBalancedBody(text, match.Index + match.Length - 1);
            var name = match.Groups["name"].Value;
            enums.TryAdd(name, new IdlEnum(name, ParseEnumValues(body)));
        }

        return new IdlModel(interfaces, enums);
    }

    private static Dictionary<string, HeaderInterface> ParseHeader(string text)
    {
        text = RemoveComments(text);
        var interfaces = new Dictionary<string, HeaderInterface>(StringComparer.Ordinal);
        foreach (Match match in HeaderInterfaceStartRegex().Matches(text))
        {
            var body = ReadBalancedBody(text, match.Index + match.Length - 1);
            var methods = HeaderMethodRegex().Matches(body).Select(static item => new HeaderMethod(
                item.Groups["name"].Value,
                ParseHeaderParameterTypes(item.Groups["parameters"].Value))).ToArray();
            var model = new HeaderInterface(match.Groups["name"].Value, match.Groups["base"].Value, match.Groups["iid"].Value, methods);
            interfaces.TryAdd(model.Name, model);
        }

        return interfaces;
    }

    private static List<IdlMethod> ParseIdlMethods(string body)
    {
        var methods = new List<IdlMethod>();
        foreach (Match match in IdlMethodRegex().Matches(body))
        {
            var prefix = match.Groups["attribute"].Value switch
            {
                "propget" => "get_",
                "propput" => "put_",
                _ => string.Empty,
            };
            var parameters = SplitParameters(match.Groups["parameters"].Value).Select(ParseParameter).ToArray();
            methods.Add(new IdlMethod(prefix + match.Groups["name"].Value, parameters));
        }

        return methods;
    }

    private static IdlParameter ParseParameter(string parameter)
    {
        parameter = ParameterAttributeRegex().Replace(parameter, string.Empty).Trim();
        var nameMatch = ParameterNameRegex().Match(parameter);
        if (!nameMatch.Success)
        {
            throw new InvalidDataException($"Unsupported selected IDL parameter '{parameter}'.");
        }

        var name = EscapeIdentifier(nameMatch.Groups["name"].Value);
        var nativeType = parameter[..nameMatch.Index].Trim();
        return new IdlParameter(name, NormalizeNativeType(nativeType), MapManagedType(nativeType));
    }

    private static string MapManagedType(string nativeType)
    {
        nativeType = nativeType.Replace("const", string.Empty, StringComparison.Ordinal).Trim();
        if (nativeType.Contains('*') || nativeType is "LPCWSTR" or "LPWSTR" or "HWND")
        {
            return "nint";
        }

        return nativeType switch
        {
            "BOOL" or "HRESULT" or "INT32" or "LONG" or "int" => "int",
            "UINT32" or "DWORD" => "uint",
            "INT64" => "long",
            "UINT64" => "ulong",
            "double" => "double",
            "float" => "float",
            "RECT" => "WebView2Rect",
            "POINT" => "WebView2Point",
            "EventRegistrationToken" => "EventRegistrationToken",
            _ when nativeType.StartsWith("COREWEBVIEW2_", StringComparison.Ordinal) => "int",
            _ => throw new InvalidDataException($"Unsupported selected IDL native type '{nativeType}'."),
        };
    }

    private static string CreateNativeSignature(IdlMethod method) =>
        $"{method.Name}({string.Join(',', method.Parameters.Select(static parameter => parameter.NativeType))})";

    private static string CreateNativeSignature(HeaderMethod method) =>
        $"{method.Name}({string.Join(',', method.ParameterTypes)})";

    private static string[] ParseHeaderParameterTypes(string parameters)
    {
        if (string.Equals(parameters.Trim(), "void", StringComparison.Ordinal) || string.IsNullOrWhiteSpace(parameters))
        {
            return [];
        }

        return SplitParameters(parameters).Select(static parameter =>
        {
            var nameMatch = ParameterNameRegex().Match(parameter);
            if (!nameMatch.Success)
            {
                throw new InvalidDataException($"Unsupported selected header parameter '{parameter}'.");
            }

            return NormalizeNativeType(parameter[..nameMatch.Index]);
        }).ToArray();
    }

    private static string NormalizeNativeType(string nativeType)
    {
        nativeType = nativeType.Replace("const", string.Empty, StringComparison.Ordinal);
        return WhitespaceRegex().Replace(nativeType, string.Empty);
    }

    private static List<IdlEnumValue> ParseEnumValues(string body)
    {
        var values = new List<IdlEnumValue>();
        var known = new Dictionary<string, long>(StringComparer.Ordinal);
        long nextValue = 0;
        foreach (var entry in body.Split(','))
        {
            var valueText = entry.Trim();
            if (valueText.Length == 0)
            {
                continue;
            }

            var parts = valueText.Split('=', 2);
            var name = parts[0].Trim();
            var value = parts.Length == 1 ? nextValue : EvaluateEnumExpression(parts[1], known);
            values.Add(new IdlEnumValue(name, value));
            known.Add(name, value);
            nextValue = value + 1;
        }

        return values;
    }

    private static long EvaluateEnumExpression(string expression, Dictionary<string, long> known)
    {
        expression = expression.Trim().Trim('(', ')').Trim();
        if (long.TryParse(expression, NumberStyles.Integer, CultureInfo.InvariantCulture, out var number))
        {
            return number;
        }

        if (expression.StartsWith("0x", StringComparison.OrdinalIgnoreCase)
            && ulong.TryParse(expression[2..].TrimEnd('u', 'U', 'l', 'L'), NumberStyles.HexNumber, CultureInfo.InvariantCulture, out var hex))
        {
            return unchecked((long)hex);
        }

        var addition = expression.Split('+', 2, StringSplitOptions.TrimEntries);
        if (addition.Length == 2 && known.TryGetValue(addition[0].Trim('(', ')', ' '), out var previous)
            && long.TryParse(addition[1].Trim('(', ')', ' '), CultureInfo.InvariantCulture, out var increment))
        {
            return previous + increment;
        }

        if (known.TryGetValue(expression, out var knownValue))
        {
            return knownValue;
        }

        throw new InvalidDataException($"Unsupported selected enum expression '{expression}'.");
    }

    private static IEnumerable<string> SplitParameters(string parameters)
    {
        var start = 0;
        var bracketDepth = 0;
        for (var index = 0; index < parameters.Length; index++)
        {
            bracketDepth += parameters[index] switch { '[' => 1, ']' => -1, _ => 0 };
            if (parameters[index] == ',' && bracketDepth == 0)
            {
                yield return parameters[start..index].Trim();
                start = index + 1;
            }
        }

        var final = parameters[start..].Trim();
        if (final.Length > 0)
        {
            yield return final;
        }
    }

    private static string ReadBalancedBody(string text, int openingBrace)
    {
        var depth = 0;
        for (var index = openingBrace; index < text.Length; index++)
        {
            depth += text[index] switch { '{' => 1, '}' => -1, _ => 0 };
            if (depth == 0)
            {
                return text[(openingBrace + 1)..index];
            }
        }

        throw new InvalidDataException("An unterminated selected declaration was found in an official WebView2 input.");
    }

    private static string RemoveComments(string text) => CommentRegex().Replace(text, string.Empty);

    private static string EscapeIdentifier(string name) => name is "event" or "object" or "string" or "base" ? $"@{name}" : name;

    private static void ValidateSpecification(InteropSpecification specification)
    {
        if (specification.SchemaVersion != 1 || string.IsNullOrWhiteSpace(specification.Namespace)
            || specification.Interfaces.Count == 0 || specification.LoaderFunctions.Count != 1
            || specification.LoaderFunctions[0] != "CreateCoreWebView2EnvironmentWithOptions")
        {
            throw new InvalidDataException("The WebView2 projection specification has an unsupported or incomplete schema.");
        }

        if (specification.Interfaces.Any(static item => string.IsNullOrWhiteSpace(item.Name) || item.Methods.Count == 0)
            || specification.Interfaces.Select(static item => item.Name).Distinct(StringComparer.Ordinal).Count() != specification.Interfaces.Count)
        {
            throw new InvalidDataException("Every selected interface must have a unique name and an explicit non-empty method allowlist.");
        }
    }

    private static void ThrowIfMissing(string path, string description)
    {
        if (!File.Exists(path))
        {
            throw new FileNotFoundException($"The {description} was not found at '{path}'.", path);
        }
    }

    private static string Hash(byte[] bytes) => Convert.ToHexStringLower(SHA256.HashData(bytes));

    private static string GetPackageVersion(string packageRoot)
    {
        var packageVersion = new DirectoryInfo(packageRoot).Name;
        if (!PackageVersionRegex().IsMatch(packageVersion))
        {
            throw new InvalidDataException($"The WebView2 package root '{packageRoot}' does not end with a valid NuGet package version.");
        }

        return packageVersion;
    }

    private static byte[] Utf8(string value) => new UTF8Encoding(encoderShouldEmitUTF8Identifier: false).GetBytes(Normalize(value));

    private static string Normalize(string value) => value.Replace("\r\n", "\n", StringComparison.Ordinal).TrimEnd() + "\n";

    [GeneratedRegex(@"\[\s*uuid\((?<iid>[0-9A-Fa-f-]+)\)[^\]]*\]\s*interface\s+(?<name>\w+)\s*:\s*(?<base>\w+)\s*\{", RegexOptions.Singleline)]
    private static partial Regex IdlInterfaceStartRegex();

    [GeneratedRegex(@"typedef\s+(?:\[[^\]]+\]\s*)?enum\s+(?<name>COREWEBVIEW2_\w+)\s*\{", RegexOptions.Singleline)]
    private static partial Regex IdlEnumStartRegex();

    [GeneratedRegex(@"(?:\[(?<attribute>propget|propput)\]\s*)?HRESULT\s+(?<name>\w+)\s*\((?<parameters>.*?)\)\s*;", RegexOptions.Singleline)]
    private static partial Regex IdlMethodRegex();

    [GeneratedRegex(@"^\d+(?:\.\d+){2,3}(?:[-+][0-9A-Za-z.-]+)?$", RegexOptions.CultureInvariant)]
    private static partial Regex PackageVersionRegex();

    [GeneratedRegex("MIDL_INTERFACE\\(\"(?<iid>[0-9A-Fa-f-]+)\"\\)\\s*(?<name>\\w+)\\s*:\\s*public\\s+(?<base>\\w+)\\s*\\{", RegexOptions.Singleline)]
    private static partial Regex HeaderInterfaceStartRegex();

    [GeneratedRegex(@"virtual\s+HRESULT\s+STDMETHODCALLTYPE\s+(?<name>\w+)\s*\((?<parameters>.*?)\)\s*=\s*0\s*;", RegexOptions.Singleline)]
    private static partial Regex HeaderMethodRegex();

    [GeneratedRegex(@"/\*.*?\*/|//[^\r\n]*", RegexOptions.Singleline)]
    private static partial Regex CommentRegex();

    [GeneratedRegex(@"\[[^\]]+\]")]
    private static partial Regex ParameterAttributeRegex();

    [GeneratedRegex(@"(?<name>[A-Za-z_]\w*)\s*$")]
    private static partial Regex ParameterNameRegex();

    [GeneratedRegex(@"\s+")]
    private static partial Regex WhitespaceRegex();
}

public sealed class InteropSpecification
{
    public int SchemaVersion { get; init; }
    public string Namespace { get; init; } = string.Empty;
    public IReadOnlyList<InterfaceSelection> Interfaces { get; init; } = [];
    public IReadOnlyList<string> Types { get; init; } = [];
    public IReadOnlyList<string> LoaderFunctions { get; init; } = [];
}

public sealed class InterfaceSelection
{
    public string Name { get; init; } = string.Empty;
    public IReadOnlyList<string> Methods { get; init; } = [];
}

public sealed class InteropManifest
{
    public int SchemaVersion { get; init; }
    public int GeneratorFormatVersion { get; init; }
    public string PackageId { get; init; } = string.Empty;
    public string PackageVersion { get; init; } = string.Empty;
    public IReadOnlyList<ManifestFile> Inputs { get; init; } = [];
    public IReadOnlyList<ManifestInterface> Interfaces { get; init; } = [];
    public ManifestOutput Output { get; init; } = new();
}

public sealed class ManifestFile
{
    public string Path { get; init; } = string.Empty;
    public string Sha256 { get; init; } = string.Empty;
}

public sealed class ManifestInterface
{
    public string Name { get; init; } = string.Empty;
    public string Iid { get; init; } = string.Empty;
    public string BaseInterface { get; init; } = string.Empty;
    public int EmittedMethodCount { get; init; }
}

public sealed class ManifestOutput
{
    public string Path { get; init; } = string.Empty;
    public int ByteLength { get; init; }
    public string Sha256 { get; init; } = string.Empty;
    public string Encoding { get; init; } = string.Empty;
    public string LineEndings { get; init; } = string.Empty;
}

[System.Text.Json.Serialization.JsonSerializable(typeof(InteropSpecification))]
[System.Text.Json.Serialization.JsonSerializable(typeof(InteropManifest))]
[System.Text.Json.Serialization.JsonSourceGenerationOptions(WriteIndented = true, PropertyNamingPolicy = System.Text.Json.Serialization.JsonKnownNamingPolicy.CamelCase)]
internal sealed partial class GeneratorJsonContext : System.Text.Json.Serialization.JsonSerializerContext;

internal sealed record IdlModel(
    IReadOnlyDictionary<string, IdlInterface> Interfaces,
    IReadOnlyDictionary<string, IdlEnum> Enums);

internal sealed record IdlInterface(string Name, string BaseName, string Iid, List<IdlMethod> Methods);

internal sealed record HeaderInterface(string Name, string BaseName, string Iid, IReadOnlyList<HeaderMethod> Methods);

internal sealed record HeaderMethod(string Name, IReadOnlyList<string> ParameterTypes);

internal sealed record ProjectedInterface(IdlInterface Interface, IReadOnlyList<IdlMethod> Methods);

internal sealed record IdlMethod(string Name, IReadOnlyList<IdlParameter> Parameters);

internal sealed record IdlParameter(string Name, string NativeType, string ManagedType);

internal sealed record IdlEnum(string Name, IReadOnlyList<IdlEnumValue> Values);

internal sealed record IdlEnumValue(string Name, long Value);

internal static class ListExtensions
{
    public static int FindLastIndex<T>(this IReadOnlyList<T> items, Func<T, bool> predicate)
    {
        for (var index = items.Count - 1; index >= 0; index--)
        {
            if (predicate(items[index]))
            {
                return index;
            }
        }

        return -1;
    }
}
